version: '3.7'

services:
  app:
    image: ${CACHE_IMAGE_URL}
    hostname: app
    domainname: dev02-smart.switch-m.biz
    environment:
      PGHOST: db
      PGUSER: switch
      PGPASSWORD: THr8Tz7sTU4p
      PGDATABASE: smart
      APP_ENV: development
      DOTENV_PMS_NAME: ${DOTENV_PMS_NAME}
      AWS_DEFAULT_REGION: ap-northeast-1
    ports:
      - 127.0.0.1:${PORT}:80
    tty: true
