version: '3.7'

services:
  testdb:
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    hostname: testdb
    domainname: smart2.local
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_INITDB_ARGS: --encoding=utf8
      POSTGRES_USER: switch
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart
      PGUSER: postgres
      PGPASSWORD:
      PGDATABASE: postgres

  cache:
    build:
      context: .
      dockerfile: ./.docker/cache/Dockerfile
    hostname: cache
    domainname: smart2.local
    tty: true

  db:
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    hostname: db
    domainname: smart2.local
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_INITDB_ARGS: --encoding=utf8
      POSTGRES_USER: switch
      POSTGRES_PASSWORD: THr8Tz7sTU4p
      POSTGRES_DB: smart
      PGUSER: postgres
      PGPASSWORD:
      PGDATABASE: postgres
    tty: true

  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    hostname: app
    domainname: smart2.local
    environment:
      PGHOST: db
      PGUSER: switch
      PGPASSWORD: THr8Tz7sTU4p
      PGDATABASE: smart
    volumes:
      - ./.docker/app/php.ini:/usr/local/etc/php/php.ini:rw
      - ./.docker/app/sites-enabled:/etc/apache2/sites-enabled:rw
      - ./:/usr/src/app:cached
    ports:
      - 127.0.0.1:80:80
    tty: true
